
# Config file for api package

FRIEND_STATUS_REMOVED = 0
FRIEND_STATUS_FRIEND = 1
FRIEND_STATUS_BLOCKED = 2

MAX_ROUNDS = 6

GAME_TYPE_NORMAL = 1
GAME_TYPE_FREESTYLE = 2

TURN_GAME_OVER = 0
TURN_GUESSING = 1
TURN_PHOTO = 2
TURN_WAITING = 3
TURN_CAN_START_ROUND = 4
